apps:
  - name: portal
    enable: true
    label: "rmmModule=rmm-portal"
    times: 10
    report: true
  - name: worker
    enable: true
    label: "rmmModule=rmm-worker"
    times: 10
    report: true