ip: 192.168.11.6
apps:
  - name: es-edgesense-portal
    enable: true
    label: "rmmModule=rmm-portal"
    times: 3
    report: true
    port: 8087
  - name: es-edgesense-worker
    enable: true
    label: "rmmModule=rmm-worker"
    times: 10
    report: true